### ISSUE TITLE
Missing requirements for ML model

### ISSUE THREAD

**Issue by jamestwebber** [rajewsky-lab/optocoder#1]
Hi there 👋 excited to try out this tool on our data.

I was looking at the requirements file and noticed that `tensorflow` is not listed there. Potentially other packages are also missing–I'm not familiar with the TF ecosystem so I made an issue rather than try to figure it out myself. 😅

**Comment by enessenel** [comment]
Hi James 👋 , 

thanks for your comment and great that you are trying the tool!

I now updated the requirements file with the final version. Please feel free to open up new issues if you encounter with other problems.
